database:
    # IP or DNS entry for MySQL instance
    address: "localhost"
    # Database that will be used
    database: "pystreaming"
    # User who has full credentials to the above DB
    user: "pystreaming"
    # Password of said user
    password: "pystreaming"

# Key used in Flask for encryption of cookies and the like.
secret_key: 'this_should_be_changed_to_something_long_and_random'
# List of themes, the first one being the default, which users should have access to.
# These should identically match the theme directories inside static/themes/
themes:
  - default
# HLS output directory as configured in your RTMP transcoding server.
hls_dir: '/path/to/hls'
# Timeout for liveness indicator, where playlists older than this many seconds are considered non-live. If not
# specified then this defaults to 5 seocnds.
live_indicator_delay: 5
# Supported video qualities if you are transcoding multiples. Must match your nginx transcoding configuration.
video_qualities:
