"""Consistent column name for streamer references.

Revision ID: 15b58cab2cbb
Revises: c56dbda68073
Create Date: 2024-06-17 00:46:20.754398

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '15b58cab2cbb'
down_revision = 'c56dbda68073'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('username', sa.String(length=256), nullable=False))
    op.drop_index('ix_events_streamer', table_name='events')
    op.create_index(op.f('ix_events_username'), 'events', ['username'], unique=False)
    op.drop_column('events', 'streamer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('streamer', mysql.VARCHAR(length=256), nullable=False))
    op.drop_index(op.f('ix_events_username'), table_name='events')
    op.create_index('ix_events_streamer', 'events', ['streamer'], unique=False)
    op.drop_column('events', 'username')
    # ### end Alembic commands ###
