"""Add column for storing default chat state.

Revision ID: 433eb8d7fc1e
Revises: 6eb8c2e8e005
Create Date: 2024-09-02 21:43:57.075710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '433eb8d7fc1e'
down_revision = '6eb8c2e8e005'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('streamersettings', sa.Column('chat', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('streamersettings', 'chat')
    # ### end Alembic commands ###
