"""Add stream password option for password-locked streams.

Revision ID: 66c1d32604cc
Revises: 061e179dc139
Create Date: 2022-07-21 00:12:45.768942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66c1d32604cc'
down_revision = '061e179dc139'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('streamersettings', sa.Column('streampass', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('streamersettings', 'streampass')
    # ### end Alembic commands ###
