"""Fix uniqueness constraint on table.

Revision ID: c56dbda68073
Revises: f2d1db94abf9
Create Date: 2024-06-10 02:17:19.832976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c56dbda68073'
down_revision = 'f2d1db94abf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pendingmessages_type', table_name='pendingmessages')
    op.drop_index('username', table_name='pendingmessages')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('username', 'pendingmessages', ['username'], unique=True)
    op.create_index('ix_pendingmessages_type', 'pendingmessages', ['type'], unique=False)
    # ### end Alembic commands ###
