"""Add pending messages table.

Revision ID: f2d1db94abf9
Revises: c3861669d1cd
Create Date: 2024-06-10 01:40:21.037881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2d1db94abf9'
down_revision = 'c3861669d1cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pendingmessages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=256), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('message', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username'),
    mysql_charset='utf8mb4'
    )
    op.create_index(op.f('ix_pendingmessages_type'), 'pendingmessages', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pendingmessages_type'), table_name='pendingmessages')
    op.drop_table('pendingmessages')
    # ### end Alembic commands ###
