"""Add description column to streamer settings.

Revision ID: ff462a1bd816
Revises: Initial revision
Create Date: 2021-01-20 17:18:44.787382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff462a1bd816'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('streamersettings', sa.Column('description', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('streamersettings', 'description')
    # ### end Alembic commands ###
